name: Lint
on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer require phpstan/phpstan --no-progress
      # TODO: change to the following line after phpstan have been added to composer.json
      # run: composer install --no-progress
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --no-progress

  php_cs_fixer:
    name: PHP-CS-Fxier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer require friendsofphp/php-cs-fixer --no-progress
      # TODO: change to the following line after php-cs-fixer have been added to composer.json
      # run: composer install --no-progress
    - name: Run PHP-CS-Fxier
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff 1>&2
